### PR TITLE
fix: infer types

### LINKED ISSUE #78: Infer returns incorrect type for object with optional properties
### Package version

2.1.0

### Describe the bug

Using Infer on vine.object generates incorrect type for optional properties.
```ts
const schema = vine.object({
  name: vine.string().optional(),
})

type Schema = Infer<typeof schema>
// generates type
type Schema = {
  name: string | undefined
}
```

It should generate property as optional. As if no data is provided, it will be completely omitted from resulting object.
```ts
type Schema = {
  name?: string
}
```

### Reproduction repo

_No response_

### PR DESCRIPTION
**Pull request by aadamcik**
### 🔗 Linked issue

#78 

### ❓ Type of change

- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Resolves #78 

### 📝 Checklist

- [x] I have linked an issue or discussion.

### CODE REVIEW

File: src/types.ts [hunk 1]
```diff
@@ -280,3 +280,21 @@ export type InferInput<Schema extends { [ITYPE]: any }> = Schema[typeof ITYPE]
...
+
+type PickUndefined<T> = {
+  [K in keyof T]: undefined extends T[K] ? K : never
+}[keyof T]
+
+type PickNotUndefined<T> = {
+  [K in keyof T]: undefined extends T[K] ? never : K
+}[keyof T]
+
+type Id<T> = T extends infer U ? { [K in keyof U]: U[K] } : never
```
Comment (thetutlage) [inline src/types.ts:292]: What does this `Id` helper does?

**Comment by thetutlage** [comment]
Related. https://github.com/adamcikado/vine/pull/1

**Comment by thetutlage** [comment]
Thanks :)

File: src/types.ts (hunk 1 above)
Comment (aadamcik) [reply src/types.ts:292]: It merges the the type.

Without `Id` it would create type like this:
```ts
{
  name: string
} & {
  age?: number | undefined
}
```

With `Id` it merges type to:
```ts
{
  name: string
  age?: number | undefined
}
```
